// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/track.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackIDRequest) Reset() {
	*x = TrackIDRequest{}
	mi := &file_proto_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackIDRequest) ProtoMessage() {}

func (x *TrackIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackIDRequest.ProtoReflect.Descriptor instead.
func (*TrackIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_track_proto_rawDescGZIP(), []int{0}
}

func (x *TrackIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AlbumId       string                 `protobuf:"bytes,3,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	ArtistId      string                 `protobuf:"bytes,4,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	DurationSec   int32                  `protobuf:"varint,5,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Genre         string                 `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,7,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTrackRequest) Reset() {
	*x = CreateTrackRequest{}
	mi := &file_proto_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrackRequest) ProtoMessage() {}

func (x *CreateTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateTrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_track_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTrackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTrackRequest) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *CreateTrackRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *CreateTrackRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *CreateTrackRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *CreateTrackRequest) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *CreateTrackRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type TrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AlbumId       string                 `protobuf:"bytes,3,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	ArtistId      string                 `protobuf:"bytes,4,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	DurationSec   int32                  `protobuf:"varint,5,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	Genre         string                 `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,7,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackResponse) Reset() {
	*x = TrackResponse{}
	mi := &file_proto_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackResponse) ProtoMessage() {}

func (x *TrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackResponse.ProtoReflect.Descriptor instead.
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return file_proto_track_proto_rawDescGZIP(), []int{2}
}

func (x *TrackResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrackResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TrackResponse) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *TrackResponse) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

func (x *TrackResponse) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *TrackResponse) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *TrackResponse) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *TrackResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_track_proto_rawDescGZIP(), []int{3}
}

var File_proto_track_proto protoreflect.FileDescriptor

const file_proto_track_proto_rawDesc = "" +
	"\n" +
	"\x11proto/track.proto\" \n" +
	"\x0eTrackIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe0\x01\n" +
	"\x12CreateTrackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\balbum_id\x18\x03 \x01(\tR\aalbumId\x12\x1b\n" +
	"\tartist_id\x18\x04 \x01(\tR\bartistId\x12!\n" +
	"\fduration_sec\x18\x05 \x01(\x05R\vdurationSec\x12\x14\n" +
	"\x05genre\x18\x06 \x01(\tR\x05genre\x12!\n" +
	"\frelease_date\x18\a \x01(\tR\vreleaseDate\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\xdb\x01\n" +
	"\rTrackResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\balbum_id\x18\x03 \x01(\tR\aalbumId\x12\x1b\n" +
	"\tartist_id\x18\x04 \x01(\tR\bartistId\x12!\n" +
	"\fduration_sec\x18\x05 \x01(\x05R\vdurationSec\x12\x14\n" +
	"\x05genre\x18\x06 \x01(\tR\x05genre\x12!\n" +
	"\frelease_date\x18\a \x01(\tR\vreleaseDate\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\a\n" +
	"\x05Empty2g\n" +
	"\fTrackService\x12+\n" +
	"\bGetTrack\x12\x0f.TrackIDRequest\x1a\x0e.TrackResponse\x12*\n" +
	"\vCreateTrack\x12\x13.CreateTrackRequest\x1a\x06.EmptyB\tZ\a./protob\x06proto3"

var (
	file_proto_track_proto_rawDescOnce sync.Once
	file_proto_track_proto_rawDescData []byte
)

func file_proto_track_proto_rawDescGZIP() []byte {
	file_proto_track_proto_rawDescOnce.Do(func() {
		file_proto_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_track_proto_rawDesc), len(file_proto_track_proto_rawDesc)))
	})
	return file_proto_track_proto_rawDescData
}

var file_proto_track_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_track_proto_goTypes = []any{
	(*TrackIDRequest)(nil),     // 0: TrackIDRequest
	(*CreateTrackRequest)(nil), // 1: CreateTrackRequest
	(*TrackResponse)(nil),      // 2: TrackResponse
	(*Empty)(nil),              // 3: Empty
}
var file_proto_track_proto_depIdxs = []int32{
	0, // 0: TrackService.GetTrack:input_type -> TrackIDRequest
	1, // 1: TrackService.CreateTrack:input_type -> CreateTrackRequest
	2, // 2: TrackService.GetTrack:output_type -> TrackResponse
	3, // 3: TrackService.CreateTrack:output_type -> Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_track_proto_init() }
func file_proto_track_proto_init() {
	if File_proto_track_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_track_proto_rawDesc), len(file_proto_track_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_track_proto_goTypes,
		DependencyIndexes: file_proto_track_proto_depIdxs,
		MessageInfos:      file_proto_track_proto_msgTypes,
	}.Build()
	File_proto_track_proto = out.File
	file_proto_track_proto_goTypes = nil
	file_proto_track_proto_depIdxs = nil
}
